### ISSUE TITLE
Scanned invalid account QR code

### ISSUE THREAD

**Issue by rhclayto** [GrapheneOS/AttestationServer#140]
When scanning the barcode created on my self-hosted Attestation Server with my Auditor app, I get the message 'Scanned invalid account QR code'. When I do the same on the attestation.app site, it successfully sets up remote verification.

I have changed the DOMAIN variable in the source code of AttestationServer.java to match my domain name (otherwise it gives a 403 Unauthorized HTTP error). I see this is also used in the AccountQrHandler class. Could it be that the Auditor app has the attestation.app domain hardcoded? Or is it something else?

Update:

It looks like it is hard-coded.

https://github.com/GrapheneOS/Auditor/blob/4750ff5c1d434e799181ca86aeec2f7b9fe3203c/app/src/main/java/app/attestation/auditor/AttestationActivity.java#L113-L116

https://github.com/GrapheneOS/Auditor/blob/main/app/src/main/java/app/attestation/auditor/RemoteVerifyJob.java#L38

Does this mean that in order to run one's own Attestation server, one needs to fork the Auditor & compile a modified apk to get them to work together?

**Comment by flawedworld** [comment]
>Does this mean that in order to run one's own Attestation server, one needs to fork the Auditor & compile a modified apk to get them to work together?

Yes, you will need to substitute values in both AttestationServer and Auditor to accommodate your setup.

**Comment by thestinger** [comment]
The official Auditor could eventually support other servers but it doesn't at the moment. There are various things to take into account for that.

**Comment by rhclayto** [comment]
> > Does this mean that in order to run one's own Attestation server, one needs to fork the Auditor & compile a modified apk to get them to work together?
> 
> Yes, you will need to substitute values in both AttestationServer and Auditor to accommodate your setup.

Thanks for confirmation. Is it possible to install a modified Auditor app on GrapheneOS, would this conflict with the one that ships with the OS?

**Comment by rhclayto** [comment]
> The official Auditor could eventually support other servers but it doesn't at the moment. There are various things to take into account for that.

It would be a nice feature.

**Comment by thestinger** [comment]
> Thanks for confirmation. Is it possible to install a modified Auditor app on GrapheneOS, would this conflict with the one that ships with the OS?

As long as you change the app id, you can install a modified one signed with your own key.
