### ISSUE TITLE
noscript message not shown

### ISSUE THREAD

**Issue by besendorf** [GrapheneOS/AttestationServer#251]
The noscript message, defined [here](https://github.com/GrapheneOS/AttestationServer/blob/main/static/index.html#L47)  is not shown on my Firefox with noscript installed and the Javascript from attestation.app blocked.

**Comment by thestinger** [comment]
That sounds like a browser issue. It works fine elsewhere.

**Comment by r3g-5z** [comment]
@besendorf The message works fine also using Firefox and NoScript with the default configuration of blocking all scripts. If you disabled `noscript` in NoScript's settings, that's the problem.
