### ISSUE TITLE
Show pretty page for when nginx shows a 502 or a 405

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/AttestationServer#268]

**Comment by thestinger** [comment]
Could simply reuse the 404 page for 405. Doesn't need to be a user-facing distinction.

**Comment by thestinger** [comment]
This is implemented for 405 errors now. GET requests aren't passed to the backend so I don't think there's a reason to make an error page for 502 errors. The web application does need to start displaying more of the possible errors to users but that's not an error page.
