### ISSUE TITLE
Remote Attestation: 48 hour delay verification

### ISSUE THREAD

**Issue by rivetrenuck** [GrapheneOS/AttestationServer#57]
Dear All, 

**> The following devices have failed to provide valid attestations before the expiry time:

> Log in to https://attestation.app/ for more information.
> If you do not want to receive these alerts and cannot log in to the account,
> email contact@attestation.app from the address receiving the alerts.**

I received the following alert. Would anyone be able to advise on what to do in response? I have logged in and can see have checked the logs but do not know what to do next.

**Comment by beerisgood** [comment]
It's already fixed.
See https://github.com/GrapheneOS/Auditor/issues/74 which is also listed in Changelog: https://grapheneos.org/releases#2020.10.01.23

**Comment by rivetrenuck** [comment]
Thank you beerisgood for linking to this thread. I am afraid I am very new to all of this and I am not clear on what I need to do in order to get Auditor to resume attestation. Could you lay out the steps? Thank you in advance for your patience and assistance.

**Comment by beerisgood** [comment]
Just wait for next GrapheneOS update and problem is solved ;)

**Comment by rivetrenuck** [comment]
Thank you very much for your help! Cheers!

**Comment by inthewaves** [comment]
You can update Auditor directly by downloading the apk of the latest version at https://github.com/GrapheneOS/Auditor/releases/tag/21

**Comment by thestinger** [comment]
If your remote verifications aren't working, the next step is to do a local verification to see what fails. The purpose of the remote verification service is to let you know that the app isn't sending valid remote attestations. Investigating why is up to you after finding out. In this case Auditor discovered a minor secure element bug and we had to work around it.
