### ISSUE TITLE
sponge not in package.json

### ISSUE THREAD

**Issue by nberlee** [GrapheneOS/AttestationServer#63]
minor nitpick:
`sponge` seems to be the only npm module needed for the `*_static` scripts which is not mentioned in `package.json`

**Comment by thestinger** [comment]
The intention is that the moreutils package is used, not the npm module. You can see it's installed in https://github.com/GrapheneOS/AttestationServer/blob/master/.github/workflows/static.yml. I'd prefer not to use npm for anything beyond what's absolutely necessary.
