### ISSUE TITLE
Investigate AppArmor confinement

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/AttestationServer#65]

**Comment by thestinger** [comment]
I don't think each service needing to provide a MAC policy is a sensible way to approach MAC. The distribution should be providing generic isolation for services. This would also be too distribution-specific for us to implement it.

We run the overall service in a dedicated virtual machine so there are very limited benefits to providing better containment. The attestation server's database is the only valuable data that's available and it inherently needs to have full read / write access to it.
