### ISSUE TITLE
Investigate further systemd confinement

### ISSUE THREAD

**Issue by flawedworld** [GrapheneOS/AttestationServer#67]

**Comment by thestinger** [comment]
I spent some time implementing this and there's not much more that could be done beyond removing more system calls.

**Comment by thestinger** [comment]
I removed some more system calls. I don't want to start listing them out by hand because it's very error prone and has to be properly maintained based on added system calls and changes in Java / libc.

**Comment by thestinger** [comment]
I removed some more system calls. I don't want to start listing them out by hand because it's very error prone and has to be properly maintained based on added system calls and changes in Java, libc and other dependencies.
