### ISSUE TITLE
How to know if a device is compromised?

### ISSUE THREAD

**Issue by aniphreak** [GrapheneOS/AttestationServer#82]
I dont see a guide anywhere on how can we practically use this. I have a dumb question:

Does if the "Verified Boot Hash" changes, meaning something happened?

**Comment by thestinger** [comment]
The service provides you with the results of the latest verification. If it stops receiving valid attestations for the configured time period, sends an alert email. It doesn't update the data based on a failed attestation. It's assumed that a sophisticated attacker will block it from reporting so it's based around alerting you if the device starts failing to provide valid attestations. 

You do not need to manually check the provided information to confirm that the device passed. That wouldn't make sense. I recommend doing a local verification as that will help you with understanding the purpose of the app.

https://attestation.app/about has further information. Your confusion seems to be that you expect that you need to check something but that's not how it works. It's checking the authenticity/integrity/identity of the device. That's the point of the app.

The information it provides to you is all in addition to the baseline of it passing the verification. That is meant for you to check to make sure that it's appropriate. It will not pass if the OS version was downgraded so you are not meant to be checking for something like that. The purpose of the app is it verifies it for you.

**Comment by thestinger** [comment]
The service provides you with the results of the latest verification. If it stops receiving valid attestations for the configured time period, sends an alert email. It doesn't update the data based on a failed attestation. It's assumed that a sophisticated attacker will block it from reporting so it's based around alerting you if the device starts failing to provide valid attestations.

You do not need to manually check the provided information to confirm that the device passed. That wouldn't make sense. I recommend doing a local verification as that will help you with understanding the purpose of the app.

https://attestation.app/about has further information. Your confusion seems to be that you expect that you need to check something but that's not how it works. It's checking the authenticity/integrity/identity of the device. That's the point of the app.

The information it provides to you is all in addition to the baseline of it passing the verification. That is meant for you to check to make sure that it's appropriate. It will not pass if the OS version was downgraded so you are not meant to be checking for something like that. If there was something else to check in an objective way, the app would simply do that itself.
